[package]
name = "ra-fast-diag-ser"
version = "0.1.0"
edition = "2021"

[dependencies]
concat-in-place = "1.1.0"
itoa = "1.0.11"
lsp-types = "0.97.0"
serde_json = "1.0.117"
sonic-rs = "0.3.7"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bench"
harness = false
